[project]
name = "minimind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.24, <2.3",
    "pandas>=2.3.3",
    "torch>=2.0.0",
    "transformers>=4.57.1",
]
